name: wavid
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  qr_code_scanner: ^1.0.1
  modal_bottom_sheet: ^3.0.0
  flutter_svg: ^2.0.10+1
  riverpod: ^2.5.1
  animations: ^2.0.11
  freezed: ^2.5.2
  flutter_spinkit: ^5.2.1
  http: ^1.2.2
  dio: ^5.5.0+1
  riverpod_annotation: ^2.3.5
  flutter_riverpod: ^2.5.1
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  spider: ^4.2.2
  flutter_keyboard: ^2.0.3
  contained_tab_bar_view: ^0.8.0
  simple_numpad: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  riverpod_lint: ^2.3.10
  custom_lint: ^0.6.4
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/svgs/

  fonts:
  - family: Pretendard
    fonts:
      - asset: assets/fonts/Pretendard-Bold.ttf
        weight: 700
      - asset: assets/fonts/Pretendard-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Pretendard-Regular.ttf
        weight: 400